apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: '{namespace}'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: '{email}'
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: '{nginx-class}'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: '{namespace}'
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: '{email}'
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: '{nginx-class}'
